import {mkdir,mkdtemp,readFile,writeFile,readdir} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawn} from 'node:child_process';
import assert from 'node:assert/strict';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const executable=resolve(process.argv[2]||resolve(root,'release/win-unpacked/Pi-desktop.exe'));
const folder=resolve(root,'.agent/verification/package');await mkdir(folder,{recursive:true});
const profile=await mkdtemp(resolve(folder,'profile-'));
const env={...process.env};for(const name of Object.keys(env))if(/API_?KEY|TOKEN|SECRET|PASSWORD|CREDENTIAL/i.test(name))delete env[name];
delete env.ELECTRON_RUN_AS_NODE;
env.PATH=[resolve(env.SystemRoot||'C:/Windows','System32'),resolve(env.SystemRoot||'C:/Windows'),resolve(env.SystemRoot||'C:/Windows','System32/WindowsPowerShell/v1.0')].join(';');
const child=spawn(executable,['--package-check','--test-profile',profile],{cwd:profile,env,windowsHide:true,stdio:['ignore','pipe','pipe']});
let output='';child.stdout.on('data',b=>output+=b);child.stderr.on('data',b=>output+=b);
const timer=setTimeout(()=>child.kill(),90000);
const code=await new Promise((accept,reject)=>{child.once('error',reject);child.once('close',accept);}).finally(()=>clearTimeout(timer));
await writeFile(resolve(profile,'launch.log'),output);
assert.equal(code,0,output);
const report=JSON.parse(await readFile(resolve(profile,'verification/package-check.json'),'utf8'));assert.deepEqual(report.errors,[]);
const bundle=resolve(dirname(executable),'resources/app'),top=await readdir(bundle);
for(const forbidden of ['.agent','.env','.npmrc','research','test','scripts','configs/keys.json'])assert(!top.includes(forbidden),'Personal and development files excluded: '+forbidden);
await writeFile(resolve(folder,'latest.json'),JSON.stringify({...report,profile,bundleTopLevel:top,systemNodeRemovedFromPath:true},null,2));
console.log(JSON.stringify({executable,checks:report.checks.length,errors:report.errors,profile,systemNodeRemovedFromPath:true}));
