import {mkdir,mkdtemp,readFile,writeFile,readdir,stat} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawn} from 'node:child_process';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const executable=resolve(process.argv[2]||resolve(root,'release/win-unpacked/Pi-desktop.exe'));
const folder=resolve(root,'.agent/verification/package');await mkdir(folder,{recursive:true});
const profile=await mkdtemp(resolve(folder,'profile-'));
const env={...process.env};for(const name of Object.keys(env))if(/API_?KEY|TOKEN|SECRET|PASSWORD|CREDENTIAL/i.test(name))delete env[name];
delete env.ELECTRON_RUN_AS_NODE;
env.PATH=[resolve(env.SystemRoot||'C:/Windows','System32'),resolve(env.SystemRoot||'C:/Windows'),resolve(env.SystemRoot||'C:/Windows','System32/WindowsPowerShell/v1.0')].join(';');
const child=spawn(executable,['--package-check','--test-profile',profile],{cwd:profile,env,windowsHide:true,stdio:['ignore','pipe','pipe']});
let output='';child.stdout.on('data',b=>output+=b);child.stderr.on('data',b=>output+=b);
const timer=setTimeout(()=>child.kill(),90000);
const code=await new Promise((accept,reject)=>{child.once('error',reject);child.once('close',accept);}).finally(()=>clearTimeout(timer));
await writeFile(resolve(profile,'launch.log'),output);
assert.equal(code,0,output);
const report=JSON.parse(await readFile(resolve(profile,'verification/package-check.json'),'utf8'));assert.deepEqual(report.errors,[]);
const archive=resolve(dirname(executable),'resources/app.asar'),packed=await stat(archive).then(()=>true,()=>false);
const bundle=packed?archive:resolve(dirname(executable),'resources/app');
const entries=packed?createRequire(import.meta.url)('@electron/asar').listPackage(archive).map(path=>path.replaceAll('\\','/').replace(/^\//,'')):await readdir(bundle,{recursive:true});
const normalized=entries.map(path=>path.replaceAll('\\','/'));
const top=[...new Set(normalized.map(path=>path.split('/')[0]))];
for(const forbidden of ['.agent','.git','.env','.npmrc','research','test','scripts','configs/keys.json','configs/auth.json'])assert(!normalized.some(path=>path===forbidden || path.startsWith(forbidden+'/')),'Personal and development files excluded: '+forbidden);
await writeFile(resolve(folder,'latest.json'),JSON.stringify({...report,profile,bundleTopLevel:top,systemNodeRemovedFromPath:true},null,2));
console.log(JSON.stringify({executable,checks:report.checks.length,errors:report.errors,profile,systemNodeRemovedFromPath:true}));
