import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,realpath} from 'node:fs/promises';
import {resolve} from 'node:path';
import {setTimeout as delay} from 'node:timers/promises';
import {app} from 'electron';
export async function runPackagingSmoke({window,actions,settings,project}){
  const checks=[],errors=[],js=code=>window.webContents.executeJavaScript(code);
  window.webContents.on('console-message',e=>{if(e.level==='error')errors.push(e.message);});
  async function until(check,label){const deadline=Date.now()+20000;while(Date.now()<deadline){if(await check())return;await delay(40);}throw new Error('Packaged check timed out: '+label);}
  assert(app.isPackaged);assert.equal(app.getName(),'Pi-desktop');assert.equal(window.getTitle(),'Pi-desktop');
  checks.push('packaged Windows application and Pi-desktop identity');
  const runtime=resolve(process.resourcesPath,'runtime'),manifest=JSON.parse(await readFile(resolve(runtime,'runtime-manifest.json'),'utf8'));
  assert(process.env.PATH.split(';')[0]===runtime);await readFile(resolve(runtime,'node.exe'));
  checks.push('bundled Node and npm take precedence without a system Node installation');
  await until(()=>js("document.getElementById('model-select').value==='demo/offline'&&!document.getElementById('send').disabled"),'renderer ready');
  assert(await js("document.querySelector('.brand strong').textContent==='Pi-desktop'"));
  await until(()=>js("document.querySelector('.brand-mark img')?.complete&&document.querySelector('.brand-mark img')?.naturalWidth>0"),'application brand image');
  checks.push('application brand SVG loads through the packaged local protocol');
  assert.equal(await js('typeof require'),'undefined');
  checks.push('real renderer and isolated preload bridge');
  const first=await actions.state();assert.equal(first.agent.engine,'pi');
  assert(first.agent.commands.some(c=>c.command==='/plan'));assert(first.agent.commands.some(c=>c.command==='/goal'));
  assert.equal(first.agent.resourceDiagnostics.filter(d=>d.type==='error').length,0);
  checks.push('Pi worker and bundled TypeScript plan and goal extensions');
  assert.equal(first.presets.length,11);assert(first.presets.reduce((n,p)=>n+p.models.length,0)>1200);
  assert(await js("document.querySelectorAll('#model-select option').length>1200"));
  checks.push('complete model directory and local UI assets');
  await js("document.getElementById('prompt').value='修改问候';document.getElementById('send').click()");
  await until(async()=>!!(await actions.state()).lastResult,'offline coding loop');
  const completed=await actions.state();assert.equal(completed.lastResult.status,'completed');
  assert.equal(await readFile(resolve(first.project,'hello.txt'),'utf8'),'Hello, coding agent!\r\n');assert.equal((await actions.changes()).length,1);
  checks.push('real utility process file tools and CRLF-preserving edit');
  await actions.setMode({mode:'plan'});assert(!(await actions.state()).agent.tools.includes('edit'));await actions.setMode({mode:'build'});
  checks.push('packaged workflow mode and restored write permissions');
  const extension=resolve(settings.folder,'package-check-extension.mjs'),runtimeResult=resolve(settings.folder,'runtime-result.json');
  await writeFile(extension,`import {writeFile} from 'node:fs/promises';export default function(pi){pi.registerCommand('package-runtime',{handler:async(args,ctx)=>{const r=await pi.exec('powershell.exe',['-NoLogo','-NoProfile','-NonInteractive','-Command','node --version; npm --version']);await writeFile(${JSON.stringify(runtimeResult)},JSON.stringify(r));if(r.code!==0)throw new Error('runtime command failed');ctx.ui.notify('PACKAGED_RUNTIME '+r.stdout.trim());}});}`);
  await actions.addResource({source:extension,scope:'global'});
  const installed=(await actions.listResources()).items.find(item=>item.path===extension);assert(installed);
  await actions.toggleResource({id:installed.id,enabled:true});
  await actions.extensionCommand({prompt:'/package-runtime'});
  await until(()=>readFile(runtimeResult).then(()=>true,()=>false),'runtime command');
  const runtimeResponse=JSON.parse(await readFile(runtimeResult,'utf8'));assert.equal(runtimeResponse.code,0,JSON.stringify(runtimeResponse));
  const commandResult=runtimeResponse.stdout;
  assert(commandResult.includes(manifest.node));assert(commandResult.includes(manifest.npm));
  checks.push('local extension loads through Pi and executes bundled node and npm');
  await actions.addPreset({presetId:'openrouter',key:'package-fixture-key',persist:true});
  const saved=await readFile(resolve(settings.folder,'keys.json'),'utf8');assert(!saved.includes('package-fixture-key'));assert((await actions.state()).keyStatus.openrouter);
  await actions.setModel({key:'demo/offline'});
  checks.push('Windows encrypted credential storage outside the application bundle');
  const restored=await actions.resume({id:first.agent.sessionId,path:first.project});assert.equal(restored.agent.sessionId,first.agent.sessionId);assert((await actions.history()).entries.length>0);
  checks.push('native session restoration and persisted history');
  assert.deepEqual(errors,[]);
  const folder=resolve(settings.folder,'verification');await mkdir(folder,{recursive:true});await delay(150);
  await writeFile(resolve(folder,'packaged-desktop.png'),(await window.webContents.capturePage(undefined,{stayHidden:true,stayAwake:true})).toPNG());
  const report={timestamp:new Date().toISOString(),executable:process.execPath,appPath:await realpath(project),userData:settings.folder,node:manifest.node,npm:manifest.npm,checks,errors};
  await writeFile(resolve(folder,'package-check.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}
